In [15]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [16]:
df = pd.read_csv("Fraud_check.csv")

In [17]:
df

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [18]:
df.shape

(600, 6)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Undergrad        600 non-null    object
 1   Marital.Status   600 non-null    object
 2   Taxable.Income   600 non-null    int64 
 3   City.Population  600 non-null    int64 
 4   Work.Experience  600 non-null    int64 
 5   Urban            600 non-null    object
dtypes: int64(3), object(3)
memory usage: 28.2+ KB


In [22]:
df.describe()

Taxable.Income  City.Population  Work.Experience
count      600.000000       600.000000       600.000000
mean     55208.375000    108747.368333        15.558333
std      26204.827597     49850.075134         8.842147
min      10003.000000     25779.000000         0.000000
25%      32871.500000     66966.750000         8.000000
50%      55074.500000    106493.500000        15.000000
75%      78611.750000    150114.250000        24.000000
max      99619.000000    199778.000000        30.000000

In [23]:
df.isnull()

Undergrad  Marital.Status  Taxable.Income  City.Population  \
0        False           False           False            False   
1        False           False           False            False   
2        False           False           False            False   
3        False           False           False            False   
4        False           False           False            False   
..         ...             ...             ...              ...   
595      False           False           False            False   
596      False           False           False            False   
597      False           False           False            False   
598      False           False           False            False   
599      False           False           False            False   

     Work.Experience  Urban  
0              False  False  
1              False  False  
2              False  False  
3              False  False  
4              False  False  
..               ...    ...  
595            False  False  
596            False  False  
597            False  False  
598            False  False  
599            False  False  

[600 rows x 6 columns]

In [24]:
df.isnull().sum()

Undergrad          0
Marital.Status     0
Taxable.Income     0
City.Population    0
Work.Experience    0
Urban              0
dtype: int64

In [42]:
from  sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

df["Undergrad"]= LE.fit_transform(df["Undergrad"])
df['Marital.Status']= LE.fit_transform (df["Marital.Status"])
df['Urban'] = LE.fit_transform(df["Urban"])

In [43]:
df.head()

Undergrad  Marital.Status  Taxable.Income  City.Population  \
0          0               2           68833            50047   
1          1               0           33700           134075   
2          0               1           36925           160205   
3          1               2           50190           193264   
4          0               1           81002            27533   

   Work.Experience  Urban  
0               10      1  
1               18      1  
2               30      1  
3               15      1  
4               28      0

In [60]:
df.loc[df['Taxable.Income'] <= 30000, "Fradulent"] = "0"
df.loc[df['Taxable.Income'] >30000, "Fradulent"] ="1"

In [51]:
df.head()

Undergrad  Marital.Status  Taxable.Income  City.Population  \
0          0               2           68833            50047   
1          1               0           33700           134075   
2          0               1           36925           160205   
3          1               2           50190           193264   
4          0               1           81002            27533   

   Work.Experience  Urban Fradulent  
0               10      1         1  
1               18      1         1  
2               30      1         1  
3               15      1         1  
4               28      0         1

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_0, *['Undergrad'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_1, *['Marital.Status'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_2, *['Taxable.Income'], **{})
chart

import numpy as np
from google.colab import autoviz

def value_plot(df, y, figscale=1):
  from matplotlib import pyplot as plt
  df[y].plot(kind='line', figsize=(8 * figscale, 4 * figscale), title=y)
  plt.gca().spines[['top', 'right']].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = value_plot(_df_3, *['City.Population'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_4, *['Undergrad'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_5, *['Marital.Status'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_6, *['Taxable.Income'], **{})
chart

import numpy as np
from google.colab import autoviz

def histogram(df, colname, num_bins=20, figscale=1):
  from matplotlib import pyplot as plt
  df[colname].plot(kind='hist', bins=num_bins, title=colname, figsize=(8*figscale, 4*figscale))
  plt.gca().spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = histogram(_df_7, *['City.Population'], **{})
chart

import numpy as np
from google.colab import autoviz

def scatter_plots(df, colname_pairs, figscale=1, alpha=.8):
  from matplotlib import pyplot as plt
  plt.figure(figsize=(len(colname_pairs) * 6 * figscale, 6 * figscale))
  for plot_i, (x_colname, y_colname) in enumerate(colname_pairs, start=1):
    ax = plt.subplot(1, len(colname_pairs), plot_i)
    df.plot(kind='scatter', x=x_colname, y=y_colname, s=(32 * figscale), alpha=alpha, ax=ax)
    ax.spines[['top', 'right',]].set_visible(False)
  plt.tight_layout()
  return autoviz.MplChart.from_current_mpl_state()

chart = scatter_plots(_df_8, *[[['Undergrad', 'Marital.Status'], ['Marital.Status', 'Taxable.Income'], ['Taxable.Income', 'City.Population'], ['City.Population', 'Work.Experience']]], **{})
chart

In [56]:
df["Fradulent"].value_counts()

1    476
0    124
Name: Fradulent, dtype: int64

In [62]:
X = df.iloc[:, :-1]
y =df.iloc[:, -1]

In [63]:
X.shape

(600, 6)

In [64]:
y.shape

(600,)

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [68]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(criterion = "gini", max_depth= 8, min_samples_split= 10, random_state= 42
                             )

In [69]:
clf.fit(X_train, y_train)

RandomForestClassifier(max_depth=8, min_samples_split=10, random_state=42)

In [70]:
clf.feature_importances_

array([0.00452539, 0.00855038, 0.90169121, 0.04994791, 0.0317014 ,
       0.0035837 ])

In [71]:
df.columns

Index(['Undergrad', 'Marital.Status', 'Taxable.Income', 'City.Population',
       'Work.Experience', 'Urban', 'Fradulent'],
      dtype='object')

In [72]:
y_pred =clf.predict(X_test)

In [73]:
y_pred

array(['0', '1', '1', '1', '0', '0', '0', '1', '1', '0', '0', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '0', '1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '0', '1', '1', '0', '1', '1', '1', '1', '1', '0',
       '1', '1', '0', '0', '1', '1', '0', '1', '1', '1', '0', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1',
       '1', '1', '1', '0', '0', '0', '1', '1', '1', '1', '1', '1', '1',
       '0', '0', '0', '1', '1', '1', '0', '1', '0', '1', '1', '1', '1',
       '1', '1', '0', '1', '1', '1', '1', '0', '1', '1', '1', '1', '0',
       '1', '1', '1', '0', '1', '0', '1', '1', '1', '0', '1', '0', '0',
       '1', '1', '1', '1', '1', '1', '1'], dtype=object)

In [75]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 32,   1],
       [  0, 117]])

In [76]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.9933333333333333

In [77]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf, X_train, y_train, cv=10)

array([1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 0.97777778, 1.        , 1.        , 1.        ])

In [78]:
from sklearn.metrics import classification_report
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98        32
           1       1.00      0.99      1.00       118

    accuracy                           0.99       150
   macro avg       0.98      1.00      0.99       150
weighted avg       0.99      0.99      0.99       150

